name: Get Feed

on:
  schedule:
    - cron: '30 12 * * *' # 6pm IST
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      RUN_FREQUENCY: 86400 # in seconds
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Repository Files
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Ensure compatibility with the Notion SDK

      - name: Install Dependencies
        run: npm install @notionhq/client

      - name: Update Notion Feed
        run: |
          node src/index.js
