name: Get Feed

on:
  schedule:
    - cron: '30 12 * * *' # 6pm IST
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      NOTION_SOURCE_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      RUN_FREQUENCY: 86400 # in seconds
    steps:
      - name: Update Notion Feed
        run: |
          curl -L -o notion-feed https://github.com/abereghici/notion-feed.rs/raw/build/build/notion-feed 
          chmod +x ./notion-feed 
          ./notion-feed
