name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM Dependencies
        id: cache-npm-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm install  # Install all dependencies

      - name: Install NPM Dependencies if not cached
        if: steps.cache-npm-dependencies.outputs.cache-hit != 'true'
        run: npm ci  # `npm ci` is preferred for CI environments

      - name: Format code with Prettier
        run: npx prettier --write .

      - name: Build Project
        run: npm run build-prod

      - name: List files in dist directory
        run: |
          echo "Listing contents of dist directory..."
          ls -R dist || echo "dist directory not found."

      - name: Check for changes in dist and commit
        run: |
          echo "Checking for changes in dist folder..."
          git add -f dist/index.js
          if [ $(git status --porcelain=v1 2>/dev/null | wc -l) -gt 0 ]; then
            echo "Changes detected in dist, committing..."
            git config user.name "GitHub Actions"
            git config user.email "noreply@github.com"
            git commit -m "chore: updated build"
            git push origin HEAD --force
          else
            echo "No changes detected in dist, skipping commit."
          fi
